### ISSUE TITLE
OSError: No file or directory found at status_detection_model.h5

### ISSUE THREAD

**Issue by Eliah-san** [Ely2112/Arknights-Auto-Clicker#1]
It won't run and I don't understand the problem. I've installed every requirement.
![Näyttökuva (40)](https://github.com/Ely2112/Arknights-Auto-Clicker/assets/130104122/07f2e1de-a63b-4ba0-b91a-429d784d12a5)

**Comment by Eliah-san** [comment]
I got that fixed, but now there's another problem. 

Traceback (most recent call last):
  File "C:\Users\rasse\main.py", line 16, in <module>
    remain_sanity, use_how_many_sanity = OCR_sanity()
                                         ^^^^^^^^^^^^
  File "C:\Users\rasse\OCR_sanity.py", line 31, in OCR_sanity
    grayImage = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' 

![Näyttökuva (41)](https://github.com/Ely2112/Arknights-Auto-Clicker/assets/130104122/6f45dcfc-377b-4493-aded-0c7a1da5e8f0)

**Comment by Ely2112** [comment]
> I got that fixed, but now there's another problem. 
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\rasse\main.py", line 16, in <module>
> 
>     remain_sanity, use_how_many_sanity = OCR_sanity()
> 
>                                          ^^^^^^^^^^^^
> 
>   File "C:\Users\rasse\OCR_sanity.py", line 31, in OCR_sanity
> 
>     grayImage = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' 
> 
> 
> 
> ![Näyttökuva (41)](https://github.com/Ely2112/Arknights-Auto-Clicker/assets/130104122/6f45dcfc-377b-4493-aded-0c7a1da5e8f0)
> 
> 


Maybe we can refer to this website 

https://github.com/ageitgey/face_recognition/issues/933

I will also check my program and rewrite the readme with more clear instructions.

I think the problem is using single or multi monitors.

Are you using single monitor?
Because I am using multiple monitors when I making this project.

Sorry I will make a single monitor  version soon.

**Comment by Eliah-san** [comment]
Hello, I was using single. Let me try multiwindow.

edit: I tried and I still got same problem. Also I forgot to mention that there was this as well:

 "I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags."

**Comment by Ely2112** [comment]
Sorry for the late reply
Seems this is not an error according to https://stackoverflow.com/questions/65298241/what-does-this-tensorflow-message-mean-any-side-effect-was-the-installation-su

<img width="690" alt="螢幕截圖 2023-09-08 下午10 17 08" src="https://github.com/Ely2112/Arknights-Auto-Clicker/assets/84430363/20262bd7-7ade-46b8-a44a-95971921c0c9">

For the opencv error, I will look up on it.

I will be back to work by tomorrow, I will make a youtube video for how to use the auto clicker :D 
Thank you for supporting this project

**Comment by Eliah-san** [comment]
Thank you for responding and I'll look forward to it. If I get this to work, it will save so many hours of repeating the same thing and no annoying macros. Good luck!!

**Comment by Ely2112** [comment]
Yes, this project also helps me a lots 🤣
I usually run this program then go to bath or do sth else and let it do its works.
